//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSentry.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceSentry.Common.Resources.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find existing service in registry..
        /// </summary>
        public static string EXCEPTION_CannotFindServiceInRegistry {
            get {
                return ResourceManager.GetString("EXCEPTION_CannotFindServiceInRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not invoke the &apos;GetInstance()&apos; method on type &apos;{0}&apos;..
        /// </summary>
        public static string EXCEPTION_CouldNotGetInstance {
            get {
                return ResourceManager.GetString("EXCEPTION_CouldNotGetInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IWindowsService cannot be null in call to WindowsServiceHarness.GetInstance()..
        /// </summary>
        public static string EXCEPTION_IWindowsServiceCannotBeNull {
            get {
                return ResourceManager.GetString("EXCEPTION_IWindowsServiceCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowsServiceDescription serviceDescription must include a service type or a service object..
        /// </summary>
        public static string EXCEPTION_ServiceDescriptionNeedsTypeOrObject {
            get {
                return ResourceManager.GetString("EXCEPTION_ServiceDescriptionNeedsTypeOrObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to install must implement a public static &apos;GetInstance()&apos; method which returns a class that inherits from WindowsService..
        /// </summary>
        public static string EXCEPTION_ServiceMustBeAbstract {
            get {
                return ResourceManager.GetString("EXCEPTION_ServiceMustBeAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to install must be marked with a WindowsServiceAttribute..
        /// </summary>
        public static string EXCEPTION_ServiceMustBeMarkedWithAttribute {
            get {
                return ResourceManager.GetString("EXCEPTION_ServiceMustBeMarkedWithAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to install must inherit from WindowsService..
        /// </summary>
        public static string EXCEPTION_ServiceMustInheritWindowsService {
            get {
                return ResourceManager.GetString("EXCEPTION_ServiceMustInheritWindowsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXCEPTION: {0}.
        /// </summary>
        public static string EXCEPTION_WithMessage {
            get {
                return ResourceManager.GetString("EXCEPTION_WithMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        public static string Info_Done {
            get {
                return ResourceManager.GetString("Info_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Client: Email Sent..
        /// </summary>
        public static string INFO_EmailSent {
            get {
                return ResourceManager.GetString("INFO_EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing &apos;{0}&apos; service..
        /// </summary>
        public static string Info_InstallingWindowsService {
            get {
                return ResourceManager.GetString("Info_InstallingWindowsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string Noun_NoKey {
            get {
                return ResourceManager.GetString("Noun_NoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Noun_Options {
            get {
                return ResourceManager.GetString("Noun_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string Noun_YesKey {
            get {
                return ResourceManager.GetString("Noun_YesKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive and Clear Logs.
        /// </summary>
        public static string Verb_ArchiveAndClearLogs {
            get {
                return ResourceManager.GetString("Verb_ArchiveAndClearLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Logs.
        /// </summary>
        public static string Verb_ArchiveLogs {
            get {
                return ResourceManager.GetString("Verb_ArchiveLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Logs (do not clear).
        /// </summary>
        public static string Verb_ArchiveLogsDoNotClear {
            get {
                return ResourceManager.GetString("Verb_ArchiveLogsDoNotClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Logs.
        /// </summary>
        public static string Verb_ClearLogs {
            get {
                return ResourceManager.GetString("Verb_ClearLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Logs (do not archive).
        /// </summary>
        public static string Verb_ClearLogsDoNotArchive {
            get {
                return ResourceManager.GetString("Verb_ClearLogsDoNotArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string Verb_Exit {
            get {
                return ResourceManager.GetString("Verb_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Logs.
        /// </summary>
        public static string Verb_IgnoreLogs {
            get {
                return ResourceManager.GetString("Verb_IgnoreLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open ServiceSentry.
        /// </summary>
        public static string Verb_OpenApplication {
            get {
                return ResourceManager.GetString("Verb_OpenApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart All Services.
        /// </summary>
        public static string Verb_RestartAllServices {
            get {
                return ResourceManager.GetString("Verb_RestartAllServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start All Services.
        /// </summary>
        public static string Verb_StartAllServices {
            get {
                return ResourceManager.GetString("Verb_StartAllServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop All Services.
        /// </summary>
        public static string Verb_StopAllServices {
            get {
                return ResourceManager.GetString("Verb_StopAllServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install this version anyway [{0}/{1}]?  .
        /// </summary>
        public static string Warn_InstallAnyway {
            get {
                return ResourceManager.GetString("Warn_InstallAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed version is newer..
        /// </summary>
        public static string Warn_InstalledVersionIsNewer {
            get {
                return ResourceManager.GetString("Warn_InstalledVersionIsNewer", resourceCulture);
            }
        }
    }
}
