//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSentry.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceSentry.Client.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string _ApplicationDescription {
            get {
                return ResourceManager.GetString("_ApplicationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceSentry.
        /// </summary>
        public static string _ApplicationName {
            get {
                return ResourceManager.GetString("_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceSentry.
        /// </summary>
        public static string _ClientName {
            get {
                return ResourceManager.GetString("_ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curtis Kaler.
        /// </summary>
        public static string _CompanyName {
            get {
                return ResourceManager.GetString("_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string AboutView_Application {
            get {
                return ResourceManager.GetString("AboutView_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression techniques from the.
        /// </summary>
        public static string AboutView_CompressionTechniques1 {
            get {
                return ResourceManager.GetString("AboutView_CompressionTechniques1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project on CodePlex..
        /// </summary>
        public static string AboutView_CompressionTechniques2 {
            get {
                return ResourceManager.GetString("AboutView_CompressionTechniques2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This computer program is protected by copyright law and international treaties.  Unauthorized reproduction or distribution of this program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law..
        /// </summary>
        public static string AboutView_CopyrightWarning {
            get {
                return ResourceManager.GetString("AboutView_CopyrightWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits:.
        /// </summary>
        public static string AboutView_Credits {
            get {
                return ResourceManager.GetString("AboutView_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons by.
        /// </summary>
        public static string AboutView_IconsBy1 {
            get {
                return ResourceManager.GetString("AboutView_IconsBy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string AboutView_IconsBy2 {
            get {
                return ResourceManager.GetString("AboutView_IconsBy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Products by Curtis Kaler:.
        /// </summary>
        public static string AboutView_InstalledProducts {
            get {
                return ResourceManager.GetString("AboutView_InstalledProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Build: .
        /// </summary>
        public static string AboutView_LastBuild {
            get {
                return ResourceManager.GetString("AboutView_LastBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed Extensibility Framework from the .
        /// </summary>
        public static string AboutView_MEF1 {
            get {
                return ResourceManager.GetString("AboutView_MEF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project on CodePlex..
        /// </summary>
        public static string AboutView_MEF2 {
            get {
                return ResourceManager.GetString("AboutView_MEF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification area icon from the .
        /// </summary>
        public static string AboutView_NotifyIcon1 {
            get {
                return ResourceManager.GetString("AboutView_NotifyIcon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to article on Code Project..
        /// </summary>
        public static string AboutView_NotifyIcon2 {
            get {
                return ResourceManager.GetString("AboutView_NotifyIcon2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string AboutView_Version {
            get {
                return ResourceManager.GetString("AboutView_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning:.
        /// </summary>
        public static string AboutView_Warning {
            get {
                return ResourceManager.GetString("AboutView_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add File.
        /// </summary>
        public static string ButtonText_AddFile {
            get {
                return ResourceManager.GetString("ButtonText_AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonText_Cancel {
            get {
                return ResourceManager.GetString("ButtonText_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ButtonText_Clear {
            get {
                return ResourceManager.GetString("ButtonText_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonText_Close {
            get {
                return ResourceManager.GetString("ButtonText_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonText_OK {
            get {
                return ResourceManager.GetString("ButtonText_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open ServiceSentry Warden in Browser.
        /// </summary>
        public static string ButtonText_OpenWarden {
            get {
                return ResourceManager.GetString("ButtonText_OpenWarden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove File.
        /// </summary>
        public static string ButtonText_RemoveFile {
            get {
                return ResourceManager.GetString("ButtonText_RemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonText_Save {
            get {
                return ResourceManager.GetString("ButtonText_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Exceptions.
        /// </summary>
        public static string ButtonText_ShowExceptions {
            get {
                return ResourceManager.GetString("ButtonText_ShowExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Warden Connection.
        /// </summary>
        public static string ButtonText_TestWarden {
            get {
                return ResourceManager.GetString("ButtonText_TestWarden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables debug mode..
        /// </summary>
        public static string CommandLine_Debug_Details {
            get {
                return ResourceManager.GetString("CommandLine_Debug_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts ServiceSentry minimized..
        /// </summary>
        public static string CommandLine_Minimized_Details {
            get {
                return ResourceManager.GetString("CommandLine_Minimized_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OPTIONS].
        /// </summary>
        public static string CommandLine_Option {
            get {
                return ResourceManager.GetString("CommandLine_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Command-Line Arguments.
        /// </summary>
        public static string CommandLineUsageView_Title {
            get {
                return ResourceManager.GetString("CommandLineUsageView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIG.
        /// </summary>
        public static string CONST_CONFIG {
            get {
                return ResourceManager.GetString("CONST_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG.
        /// </summary>
        public static string CONST_LOG {
            get {
                return ResourceManager.GetString("CONST_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created service group &apos;{0}&apos; with {1} items..
        /// </summary>
        public static string Debug_CreatedServiceGroup {
            get {
                return ResourceManager.GetString("Debug_CreatedServiceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new configuration file..
        /// </summary>
        public static string Debug_CreatingConfigFile {
            get {
                return ResourceManager.GetString("Debug_CreatingConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing extensions..
        /// </summary>
        public static string Debug_ImportingExtensions {
            get {
                return ResourceManager.GetString("Debug_ImportingExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu items published to context menu..
        /// </summary>
        public static string Debug_MenuItemsPublishedToContextMenu {
            get {
                return ResourceManager.GetString("Debug_MenuItemsPublishedToContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to publish..
        /// </summary>
        public static string Debug_NothingToPublish {
            get {
                return ResourceManager.GetString("Debug_NothingToPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing extensions..
        /// </summary>
        public static string Debug_PublishingExtensionsToMainWindow {
            get {
                return ResourceManager.GetString("Debug_PublishingExtensionsToMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing extensions to Options..
        /// </summary>
        public static string Debug_PublishingExtensionsToOptions {
            get {
                return ResourceManager.GetString("Debug_PublishingExtensionsToOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceSentry and the Monitor service automatically saves their own debug logs..
        /// </summary>
        public static string DebugOptionsView_LogFilePath_Description {
            get {
                return ResourceManager.GetString("DebugOptionsView_LogFilePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the folder where ServiceSentry should save the debug log files..
        /// </summary>
        public static string DebugOptionsView_LogFilePath_TextBox {
            get {
                return ResourceManager.GetString("DebugOptionsView_LogFilePath_TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some files, e.g. the CCMExec logs or Tomcat Catalina logs, have filenames with timestamps like 
        ///&quot;CcmExec-20131116-214758.log&quot;. To handle this (or other arbitrary sets of characters), ServiceSentry will accept the wildcard &apos;*&apos; to replace any number of characters in a filename..
        /// </summary>
        public static string Description_AddAFile {
            get {
                return ResourceManager.GetString("Description_AddAFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory &quot;{0}&quot; does not exist.{1}{2}.
        /// </summary>
        public static string Error_DirectoryDNE_1 {
            get {
                return ResourceManager.GetString("Error_DirectoryDNE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to create it?.
        /// </summary>
        public static string Error_DirectoryDNE_2 {
            get {
                return ResourceManager.GetString("Error_DirectoryDNE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error to log must be an Exception..
        /// </summary>
        public static string Error_ErrorToLogMustBeAnException {
            get {
                return ResourceManager.GetString("Error_ErrorToLogMustBeAnException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Monitor Service has encountered{0} error{1}:.
        /// </summary>
        public static string Error_MonitorServiceError {
            get {
                return ResourceManager.GetString("Error_MonitorServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart button pressed, but Service parameter is null..
        /// </summary>
        public static string Error_RestartPressedButServiceIsNull {
            get {
                return ResourceManager.GetString("Error_RestartPressedButServiceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start button pressed, but Service parameter is null..
        /// </summary>
        public static string Error_StartPressedButServiceIsNull {
            get {
                return ResourceManager.GetString("Error_StartPressedButServiceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop button pressed, but Service parameter is null..
        /// </summary>
        public static string Error_StopPressedButServiceIsNull {
            get {
                return ResourceManager.GetString("Error_StopPressedButServiceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following exception(s) occurred:.
        /// </summary>
        public static string ExceptionViewer_SummaryMessage {
            get {
                return ResourceManager.GetString("ExceptionViewer_SummaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Start.
        /// </summary>
        public static string GeneralOptionsView_AutoStart {
            get {
                return ResourceManager.GetString("GeneralOptionsView_AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically start ServiceSentry when I log on to Windows.
        /// </summary>
        public static string GeneralOptionsView_AutoStart_Checkbox {
            get {
                return ResourceManager.GetString("GeneralOptionsView_AutoStart_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceSentry can start automatically and run in the background when you log on to Windows..
        /// </summary>
        public static string GeneralOptionsView_AutoStart_Description {
            get {
                return ResourceManager.GetString("GeneralOptionsView_AutoStart_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Archive Location.
        /// </summary>
        public static string GeneralOptionsView_LogArchiveLocation {
            get {
                return ResourceManager.GetString("GeneralOptionsView_LogArchiveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the folder where ServiceSentry should save any service log archives..
        /// </summary>
        public static string GeneralOptionsView_LogArchiveLocation_Description {
            get {
                return ResourceManager.GetString("GeneralOptionsView_LogArchiveLocation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to Tray.
        /// </summary>
        public static string GeneralOptionsView_MinimizeToTray {
            get {
                return ResourceManager.GetString("GeneralOptionsView_MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to notification area when closing or minimizing..
        /// </summary>
        public static string GeneralOptionsView_MinimizeToTray_Checkbox {
            get {
                return ResourceManager.GetString("GeneralOptionsView_MinimizeToTray_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the checkbox below in order to run ServiceSentry in the background when you close (or minimize) the main window..
        /// </summary>
        public static string GeneralOptionsView_MinimizeToTray_Description {
            get {
                return ResourceManager.GetString("GeneralOptionsView_MinimizeToTray_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _General.
        /// </summary>
        public static string GeneralOptionsView_Title {
            get {
                return ResourceManager.GetString("GeneralOptionsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a File.
        /// </summary>
        public static string Header_AddAFile {
            get {
                return ResourceManager.GetString("Header_AddAFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Email Address:.
        /// </summary>
        public static string Header_AdministratorEmail {
            get {
                return ResourceManager.GetString("Header_AdministratorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceSentry Debug Logs.
        /// </summary>
        public static string Header_DebugLogs {
            get {
                return ResourceManager.GetString("Header_DebugLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging Options.
        /// </summary>
        public static string Header_DebugOptionsView {
            get {
                return ResourceManager.GetString("Header_DebugOptionsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceSentry Exception Viewer.
        /// </summary>
        public static string Header_ExceptionViewer {
            get {
                return ResourceManager.GetString("Header_ExceptionViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename:.
        /// </summary>
        public static string Header_FileName {
            get {
                return ResourceManager.GetString("Header_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Options.
        /// </summary>
        public static string Header_FileOptions {
            get {
                return ResourceManager.GetString("Header_FileOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder:.
        /// </summary>
        public static string Header_Folder {
            get {
                return ResourceManager.GetString("Header_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting Arguments:.
        /// </summary>
        public static string Header_FormattingArguments {
            get {
                return ResourceManager.GetString("Header_FormattingArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename Format:.
        /// </summary>
        public static string Header_LogFileNameFormat {
            get {
                return ResourceManager.GetString("Header_LogFileNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels to log:.
        /// </summary>
        public static string Header_LogLevels {
            get {
                return ResourceManager.GetString("Header_LogLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of emails per day:.
        /// </summary>
        public static string Header_MaxEmailsPerDay {
            get {
                return ResourceManager.GetString("Header_MaxEmailsPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of emails per minute:.
        /// </summary>
        public static string Header_MaxEmailsPerMinute {
            get {
                return ResourceManager.GetString("Header_MaxEmailsPerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        public static string Header_Message {
            get {
                return ResourceManager.GetString("Header_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Monitor Service has encountered an error..
        /// </summary>
        public static string Header_MonitorServiceError {
            get {
                return ResourceManager.GetString("Header_MonitorServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Logs.
        /// </summary>
        public static string Header_OtherLogs {
            get {
                return ResourceManager.GetString("Header_OtherLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Header_Services {
            get {
                return ResourceManager.GetString("Header_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceSentry Debug Log.
        /// </summary>
        public static string Header_ServiceSentryDebugLog {
            get {
                return ResourceManager.GetString("Header_ServiceSentryDebugLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace:.
        /// </summary>
        public static string Header_StackTrace {
            get {
                return ResourceManager.GetString("Header_StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Address:.
        /// </summary>
        public static string Header_WebAddress {
            get {
                return ResourceManager.GetString("Header_WebAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding ancillary file &apos;{0}&apos;..
        /// </summary>
        public static string Info_AddingFile {
            get {
                return ResourceManager.GetString("Info_AddingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding service &apos;{0}&apos;..
        /// </summary>
        public static string Info_AddingService {
            get {
                return ResourceManager.GetString("Info_AddingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing ancillary file &apos;{0}&apos;..
        /// </summary>
        public static string Info_RemovingFile {
            get {
                return ResourceManager.GetString("Info_RemovingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing service: &apos;{0}&apos;.
        /// </summary>
        public static string Info_RemovingService {
            get {
                return ResourceManager.GetString("Info_RemovingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing configuration file &apos;{0}&apos;..
        /// </summary>
        public static string Info_WritingConfig {
            get {
                return ResourceManager.GetString("Info_WritingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string LogView_CopyToClipboard {
            get {
                return ResourceManager.GetString("LogView_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time.
        /// </summary>
        public static string LogView_DateTime_Header {
            get {
                return ResourceManager.GetString("LogView_DateTime_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string LogView_Message_Header {
            get {
                return ResourceManager.GetString("LogView_Message_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Exception Column.
        /// </summary>
        public static string LogView_ShowExceptionColumn {
            get {
                return ResourceManager.GetString("LogView_ShowExceptionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string LogView_Type_Header {
            get {
                return ResourceManager.GetString("LogView_Type_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainView_AboutButton_Text {
            get {
                return ResourceManager.GetString("MainView_AboutButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Log.
        /// </summary>
        public static string MainView_LogButton_Text {
            get {
                return ResourceManager.GetString("MainView_LogButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string MainView_OptionsButton_Text {
            get {
                return ResourceManager.GetString("MainView_OptionsButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Method:.
        /// </summary>
        public static string NotificationOptions_DeliveryMethod {
            get {
                return ResourceManager.GetString("NotificationOptions_DeliveryMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NotificationOptions_EmailLimiter_Description {
            get {
                return ResourceManager.GetString("NotificationOptions_EmailLimiter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Notifications.
        /// </summary>
        public static string NotificationOptions_EmailNotifications {
            get {
                return ResourceManager.GetString("NotificationOptions_EmailNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically email an administrator when a service stops unexpectedly..
        /// </summary>
        public static string NotificationOptions_EmailNotifications_Checkbox {
            get {
                return ResourceManager.GetString("NotificationOptions_EmailNotifications_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceSentry can automatically alert you by email when a service stops unexpectedly..
        /// </summary>
        public static string NotificationOptions_EmailNotifications_Description {
            get {
                return ResourceManager.GetString("NotificationOptions_EmailNotifications_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable SSL:.
        /// </summary>
        public static string NotificationOptions_EnableSSL {
            get {
                return ResourceManager.GetString("NotificationOptions_EnableSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Notifications.
        /// </summary>
        public static string NotificationOptions_Header {
            get {
                return ResourceManager.GetString("NotificationOptions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Name:.
        /// </summary>
        public static string NotificationOptions_HostName {
            get {
                return ResourceManager.GetString("NotificationOptions_HostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string NotificationOptions_Port {
            get {
                return ResourceManager.GetString("NotificationOptions_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Email Address:.
        /// </summary>
        public static string NotificationOptions_SendingEmailAddress {
            get {
                return ResourceManager.GetString("NotificationOptions_SendingEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Host Information.
        /// </summary>
        public static string NotificationOptions_SMTPInfo {
            get {
                return ResourceManager.GetString("NotificationOptions_SMTPInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Noun_AllFiles {
            get {
                return ResourceManager.GetString("Noun_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*.
        /// </summary>
        public static string Noun_AllFilesFilter {
            get {
                return ResourceManager.GetString("Noun_AllFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Messages.
        /// </summary>
        public static string Noun_AllMessages {
            get {
                return ResourceManager.GetString("Noun_AllMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Services.
        /// </summary>
        public static string Noun_AllServices {
            get {
                return ResourceManager.GetString("Noun_AllServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPTIONS.
        /// </summary>
        public static string Noun_CL_Options {
            get {
                return ResourceManager.GetString("Noun_CL_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Files (.config)|*.config|All Files (*.*)|*.*.
        /// </summary>
        public static string Noun_ConfigFileFilter {
            get {
                return ResourceManager.GetString("Noun_ConfigFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Noun_FileSize {
            get {
                return ResourceManager.GetString("Noun_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Noun_Icon {
            get {
                return ResourceManager.GetString("Noun_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon and Text.
        /// </summary>
        public static string Noun_IconAndText {
            get {
                return ResourceManager.GetString("Noun_IconAndText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Files (.log)|*.log|Text Files (.txt)|*.txt|All Files (*.*)|*.*.
        /// </summary>
        public static string Noun_LogFileFilter {
            get {
                return ResourceManager.GetString("Noun_LogFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        public static string Noun_Name {
            get {
                return ResourceManager.GetString("Noun_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Noun_Options {
            get {
                return ResourceManager.GetString("Noun_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Noun_Service {
            get {
                return ResourceManager.GetString("Noun_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Noun_Text {
            get {
                return ResourceManager.GetString("Noun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE.
        /// </summary>
        public static string Noun_Usage {
            get {
                return ResourceManager.GetString("Noun_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsView_Title {
            get {
                return ResourceManager.GetString("OptionsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Name.
        /// </summary>
        public static string ServiceParametersView_CommonName {
            get {
                return ResourceManager.GetString("ServiceParametersView_CommonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Files.
        /// </summary>
        public static string ServiceParametersView_ConfigFiles_Title {
            get {
                return ResourceManager.GetString("ServiceParametersView_ConfigFiles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string ServiceParametersView_File {
            get {
                return ResourceManager.GetString("ServiceParametersView_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified.
        /// </summary>
        public static string ServiceParametersView_LastModified {
            get {
                return ResourceManager.GetString("ServiceParametersView_LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Files.
        /// </summary>
        public static string ServiceParametersView_LogFiles_Title {
            get {
                return ResourceManager.GetString("ServiceParametersView_LogFiles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string ServiceParametersView_Parameters_Title {
            get {
                return ResourceManager.GetString("ServiceParametersView_Parameters_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Service Parameters.
        /// </summary>
        public static string ServiceParametersView_Title {
            get {
                return ResourceManager.GetString("ServiceParametersView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Service Logs.
        /// </summary>
        public static string ServicesView_ClearLogs_Text {
            get {
                return ResourceManager.GetString("ServicesView_ClearLogs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the services are stopped, the log files will be deleted..
        /// </summary>
        public static string ServicesView_ClearLogs_Tooltip {
            get {
                return ResourceManager.GetString("ServicesView_ClearLogs_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log File(s).
        /// </summary>
        public static string ServicesView_Columns_LogFiles {
            get {
                return ResourceManager.GetString("ServicesView_Columns_LogFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string ServicesView_Columns_Options {
            get {
                return ResourceManager.GetString("ServicesView_Columns_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ServicesView_Columns_Status {
            get {
                return ResourceManager.GetString("ServicesView_Columns_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config File(s).
        /// </summary>
        public static string ServicesView_ConfigFiles_Header {
            get {
                return ResourceManager.GetString("ServicesView_ConfigFiles_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove Services.
        /// </summary>
        public static string ServicesView_ContextMenu_AddRemoveServices {
            get {
                return ResourceManager.GetString("ServicesView_ContextMenu_AddRemoveServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Service Parameters.
        /// </summary>
        public static string ServicesView_ContextMenu_ModifyServiceParameters {
            get {
                return ResourceManager.GetString("ServicesView_ContextMenu_ModifyServiceParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string ServicesView_FileName_Header {
            get {
                return ResourceManager.GetString("ServicesView_FileName_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the &quot;.
        /// </summary>
        public static string ServicesView_FolderLink_Tooltip1 {
            get {
                return ResourceManager.GetString("ServicesView_FolderLink_Tooltip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; folder..
        /// </summary>
        public static string ServicesView_FolderLink_Tooltip2 {
            get {
                return ResourceManager.GetString("ServicesView_FolderLink_Tooltip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Service Logs.
        /// </summary>
        public static string ServicesView_IgnoreLogs_Text {
            get {
                return ResourceManager.GetString("ServicesView_IgnoreLogs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do nothing with the log files..
        /// </summary>
        public static string ServicesView_IgnoreLogs_Tooltip {
            get {
                return ResourceManager.GetString("ServicesView_IgnoreLogs_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string ServicesView_Items_Header {
            get {
                return ResourceManager.GetString("ServicesView_Items_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified.
        /// </summary>
        public static string ServicesView_LastModified_Header {
            get {
                return ResourceManager.GetString("ServicesView_LastModified_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs will be archived to: .
        /// </summary>
        public static string ServicesView_LogArchiveLocation_Text {
            get {
                return ResourceManager.GetString("ServicesView_LogArchiveLocation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log File Columns.
        /// </summary>
        public static string ServicesView_LogFileColumns_Header {
            get {
                return ResourceManager.GetString("ServicesView_LogFileColumns_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Name.
        /// </summary>
        public static string ServicesView_LogName_Header {
            get {
                return ResourceManager.GetString("ServicesView_LogName_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Service Logs.
        /// </summary>
        public static string ServicesView_LogOptions_ArchiveServiceLogs {
            get {
                return ResourceManager.GetString("ServicesView_LogOptions_ArchiveServiceLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the services are stopped, the archives will be collected, zipped, and placed in the .
        /// </summary>
        public static string ServicesView_LogOptions_ArchiveServiceLogs_Tooltip1 {
            get {
                return ResourceManager.GetString("ServicesView_LogOptions_ArchiveServiceLogs_Tooltip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  folder..
        /// </summary>
        public static string ServicesView_LogOptions_ArchiveServiceLogs_Tooltip2 {
            get {
                return ResourceManager.GetString("ServicesView_LogOptions_ArchiveServiceLogs_Tooltip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On service stop/restart:.
        /// </summary>
        public static string ServicesView_LogOptions_Group_Header {
            get {
                return ResourceManager.GetString("ServicesView_LogOptions_Group_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Path.
        /// </summary>
        public static string ServicesView_LogPath_Header {
            get {
                return ResourceManager.GetString("ServicesView_LogPath_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open containing folder.
        /// </summary>
        public static string ServicesView_OpenContainingFolder {
            get {
                return ResourceManager.GetString("ServicesView_OpenContainingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string ServicesView_Options {
            get {
                return ResourceManager.GetString("ServicesView_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Files.
        /// </summary>
        public static string ServicesView_OtherFiles_Header {
            get {
                return ResourceManager.GetString("ServicesView_OtherFiles_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.
        /// </summary>
        public static string ServicesView_Quote {
            get {
                return ResourceManager.GetString("ServicesView_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart All.
        /// </summary>
        public static string ServicesView_RestartAllButton_Text {
            get {
                return ResourceManager.GetString("ServicesView_RestartAllButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop all services (in the order specified), and then restart the services (in the order specified)..
        /// </summary>
        public static string ServicesView_RestartAllButton_Tooltip {
            get {
                return ResourceManager.GetString("ServicesView_RestartAllButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string ServicesView_RestartButton_Text {
            get {
                return ResourceManager.GetString("ServicesView_RestartButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Group.
        /// </summary>
        public static string ServicesView_RestartGroup {
            get {
                return ResourceManager.GetString("ServicesView_RestartGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarts all the services in this service group..
        /// </summary>
        public static string ServicesView_RestartGroup_Description {
            get {
                return ResourceManager.GetString("ServicesView_RestartGroup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start or restart the service..
        /// </summary>
        public static string ServicesView_Start_Description {
            get {
                return ResourceManager.GetString("ServicesView_Start_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start All.
        /// </summary>
        public static string ServicesView_StartAllButton_Text {
            get {
                return ResourceManager.GetString("ServicesView_StartAllButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start all services (in the order specified)..
        /// </summary>
        public static string ServicesView_StartAllButton_Tooltip {
            get {
                return ResourceManager.GetString("ServicesView_StartAllButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string ServicesView_StartButton_Text {
            get {
                return ResourceManager.GetString("ServicesView_StartButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Group.
        /// </summary>
        public static string ServicesView_StartGroup {
            get {
                return ResourceManager.GetString("ServicesView_StartGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts all the services in this service group..
        /// </summary>
        public static string ServicesView_StartGroup_Description {
            get {
                return ResourceManager.GetString("ServicesView_StartGroup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ServicesView_Status {
            get {
                return ResourceManager.GetString("ServicesView_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the service..
        /// </summary>
        public static string ServicesView_Stop_Description {
            get {
                return ResourceManager.GetString("ServicesView_Stop_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop All.
        /// </summary>
        public static string ServicesView_StopAllButton_Text {
            get {
                return ResourceManager.GetString("ServicesView_StopAllButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops all services (in the order specified)..
        /// </summary>
        public static string ServicesView_StopAllButton_Tooltip {
            get {
                return ResourceManager.GetString("ServicesView_StopAllButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string ServicesView_StopButton_Text {
            get {
                return ResourceManager.GetString("ServicesView_StopButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Group.
        /// </summary>
        public static string ServicesView_StopGroup {
            get {
                return ResourceManager.GetString("ServicesView_StopGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops all the services in this service group..
        /// </summary>
        public static string ServicesView_StopGroup_Description {
            get {
                return ResourceManager.GetString("ServicesView_StopGroup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;none&gt;.
        /// </summary>
        public static string Text_None {
            get {
                return ResourceManager.GetString("Text_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file using the Browse button, then make any wildcard replacements..
        /// </summary>
        public static string TextBox_AddAFile {
            get {
                return ResourceManager.GetString("TextBox_AddAFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warden Server.
        /// </summary>
        public static string Title_WardenOptions {
            get {
                return ResourceManager.GetString("Title_WardenOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string ToggleView_DisplayName {
            get {
                return ResourceManager.GetString("ToggleView_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Services:.
        /// </summary>
        public static string ToggleView_InstalledServices {
            get {
                return ResourceManager.GetString("ToggleView_InstalledServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        public static string ToggleView_ServiceName {
            get {
                return ResourceManager.GetString("ToggleView_ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Services.
        /// </summary>
        public static string ToggleView_Title {
            get {
                return ResourceManager.GetString("ToggleView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; changed on [{1}] {2}.
        /// </summary>
        public static string Trace_PropertyChanged {
            get {
                return ResourceManager.GetString("Trace_PropertyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a port number in the range: {0} - {1}..
        /// </summary>
        public static string Validation_BadPortError {
            get {
                return ResourceManager.GetString("Validation_BadPortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !.
        /// </summary>
        public static string Validation_FAIL {
            get {
                return ResourceManager.GetString("Validation_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Configuration Files.
        /// </summary>
        public static string Verb_AddConfigFiles {
            get {
                return ResourceManager.GetString("Verb_AddConfigFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add File.
        /// </summary>
        public static string Verb_AddFile {
            get {
                return ResourceManager.GetString("Verb_AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Log Files.
        /// </summary>
        public static string Verb_AddLogFiles {
            get {
                return ResourceManager.GetString("Verb_AddLogFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Verb_Browse {
            get {
                return ResourceManager.GetString("Verb_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Verb_Clear {
            get {
                return ResourceManager.GetString("Verb_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Verb_Close {
            get {
                return ResourceManager.GetString("Verb_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy all to clipboard.
        /// </summary>
        public static string Verb_CopyAllToClipboard {
            get {
                return ResourceManager.GetString("Verb_CopyAllToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove File.
        /// </summary>
        public static string Verb_RemoveFile {
            get {
                return ResourceManager.GetString("Verb_RemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Verb_Restart {
            get {
                return ResourceManager.GetString("Verb_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Verb_Save {
            get {
                return ResourceManager.GetString("Verb_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Verb_Start {
            get {
                return ResourceManager.GetString("Verb_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Verb_Stop {
            get {
                return ResourceManager.GetString("Verb_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Log File Path.
        /// </summary>
        public static string Verb_UpdateLogFilePath {
            get {
                return ResourceManager.GetString("Verb_UpdateLogFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Wrap text.
        /// </summary>
        public static string Verb_WrapText {
            get {
                return ResourceManager.GetString("Verb_WrapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows services can be monitored from the web through a ServiceSentry Warden..
        /// </summary>
        public static string WardenOptions_Server_Description {
            get {
                return ResourceManager.GetString("WardenOptions_Server_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable communication between this machine and a Warden server..
        /// </summary>
        public static string WardenOptions_UpdateWarden_Checkbox {
            get {
                return ResourceManager.GetString("WardenOptions_UpdateWarden_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceSentry Monitor service is not available..
        /// </summary>
        public static string Warn_MonitorServiceNotAvailable {
            get {
                return ResourceManager.GetString("Warn_MonitorServiceNotAvailable", resourceCulture);
            }
        }
    }
}
