//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSentry.Monitor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceSentry.Monitor.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service endpoint received START command for &apos;{0}&apos;..
        /// </summary>
        public static string Debug_EndpointReceivedSTART {
            get {
                return ResourceManager.GetString("Debug_EndpointReceivedSTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service endpoint received STOP command for &apos;{0}&apos;..
        /// </summary>
        public static string Debug_EndpointReceivedSTOP {
            get {
                return ResourceManager.GetString("Debug_EndpointReceivedSTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service endpoint received subscription for &apos;{0}&apos;..
        /// </summary>
        public static string Debug_EndpointReceivedSubscription {
            get {
                return ResourceManager.GetString("Debug_EndpointReceivedSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service endpoint received unsubscription for &apos;{0}&apos;..
        /// </summary>
        public static string Debug_EndpointReceivedUnsubscription {
            get {
                return ResourceManager.GetString("Debug_EndpointReceivedUnsubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service endpoint received subscription update for &apos;{0}&apos;..
        /// </summary>
        public static string Debug_EndpointReceivedUpdate {
            get {
                return ResourceManager.GetString("Debug_EndpointReceivedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonitorEndpoint.Refresh({0}).
        /// </summary>
        public static string Debug_MonitorRefresh {
            get {
                return ResourceManager.GetString("Debug_MonitorRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerLocalMediator.Refresh({0}).
        /// </summary>
        public static string Debug_ServerMediatorRefresh {
            get {
                return ResourceManager.GetString("Debug_ServerMediatorRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down..
        /// </summary>
        public static string Debug_ShuttingDown {
            get {
                return ResourceManager.GetString("Debug_ShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribed from services..
        /// </summary>
        public static string Debug_UnsubscribeAll {
            get {
                return ResourceManager.GetString("Debug_UnsubscribeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watchlist disposed..
        /// </summary>
        public static string Debug_WatchlistDisposed {
            get {
                return ResourceManager.GetString("Debug_WatchlistDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open the service host for {0}..
        /// </summary>
        public static string Error_CannotOpenHost {
            get {
                return ResourceManager.GetString("Error_CannotOpenHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open the service host for {0}.  The address reports access denied..
        /// </summary>
        public static string Error_CannotOpenHost_AccessDenied {
            get {
                return ResourceManager.GetString("Error_CannotOpenHost_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open the service host for {0}.  The address is already in use..
        /// </summary>
        public static string Error_CannotOpenHost_AddressInUse {
            get {
                return ResourceManager.GetString("Error_CannotOpenHost_AddressInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Command: {0}.
        /// </summary>
        public static string Error_InvalidCommand {
            get {
                return ResourceManager.GetString("Error_InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXCEPTION: {0}.
        /// </summary>
        public static string EXCEPTION {
            get {
                return ResourceManager.GetString("EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;ServerLocalMediator.Status: controller is null.&quot;.
        /// </summary>
        public static string EXCEPTION_ControllerIsNull {
            get {
                return ResourceManager.GetString("EXCEPTION_ControllerIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint: {0}.
        /// </summary>
        public static string Noun_Endpoint {
            get {
                return ResourceManager.GetString("Noun_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        public static string Status_Done {
            get {
                return ResourceManager.GetString("Status_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading config file....
        /// </summary>
        public static string Status_ReadingConfigFile {
            get {
                return ResourceManager.GetString("Status_ReadingConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service stopped..
        /// </summary>
        public static string Status_ServiceStopped {
            get {
                return ResourceManager.GetString("Status_ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribing to {0} services..
        /// </summary>
        public static string Trace_Subscribing {
            get {
                return ResourceManager.GetString("Trace_Subscribing", resourceCulture);
            }
        }
    }
}
